Lisätty opetukset järjestämismuoto rajoitteisiin
CSCfi/oiva-frontend pull request #596
Opened 2020-11-02 09:30 UTC by OlliTiillikainen

2020-11-03 15:35 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +  console.info(asetus, changeObjects, opetuksenjarjestamismuodot, locale);
console.info pois

2020-11-03 15:53 UTC, rapitkan requested changes

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +              console.log(changeObjects);
console.infot pois

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +              console.info(changeObj);
console.info pois

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +  const mapIndexed = addIndex(map);
Hyvä. Uuden funktion luonti tällä tavoin on hyödyllistä, jos funktiota käytetään useammassa koodin kohdassa.

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +              const anchor = `opetuksenJarjestamismuodot.${index}.valinta`;
Juoksevan indeksin käyttäminen ankkurissa on ongelmallista ja virhealtista, koska opetuksen järjestämismuotojen järjestys ei välttämättä ole aina sama ja toteutus menee rikki, jos esim. tulee uusi järjestämismuoto aiempien väliin. Silloin indeksit eivät enää täsmää ja muutosobjektin hakeminen palauttaa väärän muutosobjektin tai ei muutosobjektia lainkaan. Indeksin tilalla on parempi käyttää opetuksen järjestämismuodon yksilöivää tunnistetietoa. Sellaisia sovelluksessa ovat esim. koodiarvo ja uuid.

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +    };
Tämä on osuus, jota tarvitaan lähes kaikkien rajoitusten kohdalla, joten osuuden voisi eriyttää omaksi funktiokseen, luoda lokalisoinnit ja ottaa ne käyttöön.

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js
> +import opetuksenJarjestamismuoto from "./rajoitukset/4-opetuksenjarjestamismuoto";
Hyvä. Opetuksen järjestämismuotoa koskeva osuus on omassa tiedostossaan.

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js
> -import getOpetustehtavatLomake from "./rajoitukset/1-opetustehtavat";
Tämän rivin poistaminen aiheuttaa sen, ettei npm-pohjainen käännöskomento extract:messages enää toimi. Tiedostossa 1-opetustehtavat tulisi olla funktio `getOpetustehtavatLomake`.

2020-11-03 15:53 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js
>    opetustehtavat: "1. Opetus, jota lupa koskee"
Nämä voisi hiljalleen lokalisoida __(:n avulla. Tämän ehtii tehdä myöhemminkin, joten tämä ei vaikuta katselmoinnin lopputulokseen minun kohdallani.

2020-11-04 06:42 UTC, OlliTiillikainen commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +              const anchor = `opetuksenJarjestamismuodot.${index}.valinta`;
Tässä pitäisi muuttaa lomakkeen toimintaa, koska noita indeksejä käytetään siellä muutosobjektissa ja tuon on vastavattava niiden ankkureita

2020-11-06 09:02 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoite.js
> +import getOpetustehtavatLomake from "./rajoitukset/1-opetustehtavat";
Hyvä, että funktio `getOpetustetavatLomake` nyt importataan. Sitä ei tosin käytetä missään kohtaa tiedostoa, vaan käytössä on edelleen riviä ylempänä käyttöön otettu `opetustehtavat`. Rivi `import opetustehtavat from "./rajoitukset/1-opetustehtavat";` tulee poistaa ja varmistaa, että `getOpetustehtavatLomake` on käyttössä.

2020-11-06 09:04 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +import { getChangeObjByAnchor } from "../../../../../components/02-organisms/CategorizedListRoot/utils";
Hyvä! okm-frontend-components -kirjasto ei ole enää käytössä ja komponentteja käytetään lokaalisti. Viittauksen komponenttiin voi tehdä myös aloittaen `components/`, mutta tässä nähty tapa on myös ok ja se onkin paljon käytössä.

2020-11-06 09:04 UTC, rapitkan commented on src/services/lomakkeet/esi-ja-perusopetus/rajoitteet/rajoitukset/4-opetuksenjarjestamismuoto.js
> +              const anchor = `opetuksenJarjestamismuodot.${opetuksenjarjestamismuodot.koodiarvo}.valinta`;
Hyvä. Indeksiä ei enää käytetä, vaan ankkuria identifioimaan on otettu koodiarvo.

2020-11-06 09:06 UTC, rapitkan requested changes
Huolehditaan siitä, että getOpetustehtavatLomake on käytössä ja riviä ylempänä oleva import-rivi otettu pois.

2020-11-06 09:59 UTC, rapitkan approved these changes
Hyvä. Opetuksen järjestämismuoto on valittavissa valikosta. Toteutus täyttää issuen minimivaatimuksen. Asioita, jotka jäi tässä tekemättä voidaan tehdä jonkin uuden issuen piirissä:

- Käännökset
- Ei valintamahdollisuutta -merkkauksen eriyttäminen lomakerakenteesta uudelleenkäytettäväksi rakenteeksi.
- Opetuksen järjestämismuodon valitseminen oletuksena valintaelementtiin, koska kyseessä on radio button -valinta ja sen vuoksi vaihtoehtoja on vain yksi.
- Autocompleten isMulti-parametrin määrittäminen arvoon false
-

2020-11-06 10:20 UTC, merged