CSCOIVA-1540: Uuden yhteistyösopimuksen lisääminen puuttuu jos luvassa on jo joku yhteistyösopimus
CSCfi/oiva-frontend pull request #617
Opened 2020-11-10 13:23 UTC by rapitkan

2020-11-11 09:13 UTC, jleppnen requested changes
En saa tätä toimimaan cscoiva-1540_1 branchista uusimmilla backendin koodeilla.

-Jos KJ:lla on yhteistyösopimus, tulee virhe kun yrittää luoda uutta muutospyyntöä. (esim. etelä-savon koulutus oy.

-Muilla KJ:lla ei yhteistyösopimuscheckbox täyttämällä synny tekstikenttää, eikä checkboxin arvo tallennu.

2020-11-13 11:20 UTC, rapitkan commented
> En saa tätä toimimaan cscoiva-1540_1 branchista uusimmilla backendin koodeilla.
> 
> -Jos KJ:lla on yhteistyösopimus, tulee virhe kun yrittää luoda uutta muutospyyntöä. (esim. etelä-savon koulutus oy.
> 
> -Muilla KJ:lla ei yhteistyösopimuscheckbox täyttämällä synny tekstikenttää, eikä checkboxin arvo tallennu.

Mergesin developin tän PR:n koodeihin ja testaan toimintaa.

2020-11-16 07:45 UTC, jleppnen requested changes
KJ:lle jolla ei yhteistyösopimuksia pohjalla:
-En saa yhteistyösopimukset -tekstikenttää ilmestymään, eikä checkboxin arvo tallennu.

KJ:lle, jolla on yhteistyösopimus pohjalla:
-Tekstikenttä näkyy ja arvo tallentuu, mutta jos luvan päättää ja tekee uuden luvan, kaatuu homma lupaParseriin.

2021-03-09 10:33 UTC, closed without merging

2021-03-09 10:35 UTC, rapitkan commented
Suljen tämän PR:n, koska se on päässyt vanhentumaan liikaa. Lienee paljon helpompi tehdä toteutus uudestaan tuoreen koodipohjan päälle, kuin selvittää useita kymmeniä haastavia yhdistämisongelmia.