Rajoitteisiin voi valita yhden tai useamman oppilaitoksen.
CSCfi/oiva-frontend pull request #741
Opened 2021-02-16 14:42 UTC by rapitkan

2021-02-17 07:55 UTC, vrouvinen requested changes
Oppilaitos rajoitteen tallennuksessa pitäisi koodisto olla 'oppilaitos', koodiarvo '1' ja orgOid '1.2.3.444444' oppilaitoksen oid arvo.
Tällä tavalla on jo VST puolella määritelty oppilaitos määräyksiä.

2021-02-17 12:52 UTC, vrouvinen requested changes

2021-02-17 12:52 UTC, vrouvinen commented on src/helpers/rajoitteetHelper.js
> +          orgOid:
orgOid property pitäisi olla muutoksen root tasolla eikä metan sisällä.

2021-02-18 07:58 UTC, rapitkan commented on src/helpers/rajoitteetHelper.js
> +          orgOid:
OK, siirrän sen.

2021-02-18 09:56 UTC, vrouvinen approved these changes

2021-02-18 10:16 UTC, merged