CSCOIVA-1987: Lukio: Saman koulutuksen järjestäjän lupien erottaminen
CSCfi/oiva-frontend pull request #871
Opened 2021-04-16 10:38 UTC by rapitkan

2021-04-16 13:49 UTC, rapitkan commented
PR sisältää myös CSCOIVA-1934:n koodit, joten CSCOIVA-1934:n PR:ää ei käytännössä tarvitse katselmoida, jos katselmoi tämän.

2021-04-19 07:57 UTC, vrouvinen requested changes

2021-04-19 07:57 UTC, vrouvinen commented on src/utils/asiatUtils.js
> +            ? ` (${formatMessage(languages.ruotsinkielinen)})`
Tiketin mukaan tässä asianhallinassa pitäisi olla (SV).

2021-04-19 08:12 UTC, rapitkan commented on src/utils/asiatUtils.js
> +            ? ` (${formatMessage(languages.ruotsinkielinen)})`
Jeps. Vaihdetaan, niin ei ole niin tylsän samanlainen merkkaus molemmissa kohdissa.

2021-04-19 08:21 UTC, vrouvinen approved these changes

2021-04-19 11:44 UTC, merged